//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba16
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts_SupplierInfo
    {
        public int НомерДоговора { get; set; }
        public Nullable<System.DateTime> ДатаДоговора { get; set; }
        public string Название_Фамилия { get; set; }
        public string Коментарий { get; set; }
    }
}
